[site]
name = "NekoCAS"
port = 8000
icp = ""
salt = ""
security_key = ""
csrf_key = ""

[mysql]
user = ""
password = ""
addr = "tcp(localhost:3306)"
name = ""

[redis]
addr = "127.0.0.1:6379"
password = ""

[mail]
account = ""
password = ""
smtp = ""
port = 465